# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deployments.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deployments.proto',
  package='deployments',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x64\x65ployments.proto\x12\x0b\x64\x65ployments\"&\n\rUploadRequest\x12\x15\n\rdeploymentZip\x18\x01 \x01(\x0c\"%\n\x0eUploadResponse\x12\x13\n\x0buploadedKey\x18\x01 \x01(\t2R\n\x0b\x44\x65ployments\x12\x43\n\x06Upload\x12\x1a.deployments.UploadRequest\x1a\x1b.deployments.UploadResponse\"\x00\x62\x06proto3')
)




_UPLOADREQUEST = _descriptor.Descriptor(
  name='UploadRequest',
  full_name='deployments.UploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deploymentZip', full_name='deployments.UploadRequest.deploymentZip', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=72,
)


_UPLOADRESPONSE = _descriptor.Descriptor(
  name='UploadResponse',
  full_name='deployments.UploadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uploadedKey', full_name='deployments.UploadResponse.uploadedKey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['UploadRequest'] = _UPLOADREQUEST
DESCRIPTOR.message_types_by_name['UploadResponse'] = _UPLOADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadRequest = _reflection.GeneratedProtocolMessageType('UploadRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADREQUEST,
  __module__ = 'deployments_pb2'
  # @@protoc_insertion_point(class_scope:deployments.UploadRequest)
  ))
_sym_db.RegisterMessage(UploadRequest)

UploadResponse = _reflection.GeneratedProtocolMessageType('UploadResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADRESPONSE,
  __module__ = 'deployments_pb2'
  # @@protoc_insertion_point(class_scope:deployments.UploadResponse)
  ))
_sym_db.RegisterMessage(UploadResponse)



_DEPLOYMENTS = _descriptor.ServiceDescriptor(
  name='Deployments',
  full_name='deployments.Deployments',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=113,
  serialized_end=195,
  methods=[
  _descriptor.MethodDescriptor(
    name='Upload',
    full_name='deployments.Deployments.Upload',
    index=0,
    containing_service=None,
    input_type=_UPLOADREQUEST,
    output_type=_UPLOADRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEPLOYMENTS)

DESCRIPTOR.services_by_name['Deployments'] = _DEPLOYMENTS

# @@protoc_insertion_point(module_scope)
