# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import jobs_pb2 as jobs__pb2


class JobsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddJobRevision = channel.unary_unary(
        '/jobs.Jobs/AddJobRevision',
        request_serializer=jobs__pb2.AddJobRevisionRequest.SerializeToString,
        response_deserializer=jobs__pb2.AddJobRevisionResponse.FromString,
        )
    self.GetJobRevisions = channel.unary_unary(
        '/jobs.Jobs/GetJobRevisions',
        request_serializer=jobs__pb2.GetJobRevisionsRequest.SerializeToString,
        response_deserializer=jobs__pb2.GetJobRevisionsResponse.FromString,
        )
    self.GetJobRevisionByID = channel.unary_unary(
        '/jobs.Jobs/GetJobRevisionByID',
        request_serializer=jobs__pb2.GetJobRevisionByIDRequest.SerializeToString,
        response_deserializer=jobs__pb2.JobRevision.FromString,
        )
    self.GetCurrentJobRevision = channel.unary_unary(
        '/jobs.Jobs/GetCurrentJobRevision',
        request_serializer=jobs__pb2.GetJobRevisionsRequest.SerializeToString,
        response_deserializer=jobs__pb2.JobRevision.FromString,
        )
    self.RunJobRevision = channel.unary_unary(
        '/jobs.Jobs/RunJobRevision',
        request_serializer=jobs__pb2.RunJobRevisionRequest.SerializeToString,
        response_deserializer=jobs__pb2.JobRevision.FromString,
        )


class JobsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddJobRevision(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetJobRevisions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetJobRevisionByID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCurrentJobRevision(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunJobRevision(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_JobsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddJobRevision': grpc.unary_unary_rpc_method_handler(
          servicer.AddJobRevision,
          request_deserializer=jobs__pb2.AddJobRevisionRequest.FromString,
          response_serializer=jobs__pb2.AddJobRevisionResponse.SerializeToString,
      ),
      'GetJobRevisions': grpc.unary_unary_rpc_method_handler(
          servicer.GetJobRevisions,
          request_deserializer=jobs__pb2.GetJobRevisionsRequest.FromString,
          response_serializer=jobs__pb2.GetJobRevisionsResponse.SerializeToString,
      ),
      'GetJobRevisionByID': grpc.unary_unary_rpc_method_handler(
          servicer.GetJobRevisionByID,
          request_deserializer=jobs__pb2.GetJobRevisionByIDRequest.FromString,
          response_serializer=jobs__pb2.JobRevision.SerializeToString,
      ),
      'GetCurrentJobRevision': grpc.unary_unary_rpc_method_handler(
          servicer.GetCurrentJobRevision,
          request_deserializer=jobs__pb2.GetJobRevisionsRequest.FromString,
          response_serializer=jobs__pb2.JobRevision.SerializeToString,
      ),
      'RunJobRevision': grpc.unary_unary_rpc_method_handler(
          servicer.RunJobRevision,
          request_deserializer=jobs__pb2.RunJobRevisionRequest.FromString,
          response_serializer=jobs__pb2.JobRevision.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'jobs.Jobs', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
