# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deployments.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deployments.proto',
  package='deployments',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x64\x65ployments.proto\x12\x0b\x64\x65ployments\"Y\n\rUploadRequest\x12\x10\n\x08imageZip\x18\x01 \x01(\x0c\x12\x11\n\tprojectID\x18\x02 \x01(\t\x12\x0f\n\x07jobName\x18\x03 \x01(\t\x12\x12\n\ndockerfile\x18\x04 \x01(\t\"&\n\x13\x43reateImageResponse\x12\x0f\n\x07imageID\x18\x01 \x01(\t\"6\n\x0fGetImageRequest\x12\x10\n\x08imageTag\x18\x01 \x01(\t\x12\x11\n\tprojectID\x18\x02 \x01(\t\"b\n\x05Image\x12\x0f\n\x07imageID\x18\x01 \x01(\t\x12\x11\n\tprojectID\x18\x02 \x01(\t\x12\x0f\n\x07jobName\x18\x03 \x01(\t\x12\x12\n\ndockerfile\x18\x04 \x01(\t\x12\x10\n\x08imageTag\x18\x05 \x01(\t2\x97\x01\n\x0b\x44\x65ployments\x12H\n\x06Upload\x12\x1a.deployments.UploadRequest\x1a .deployments.CreateImageResponse\"\x00\x12>\n\x08GetImage\x12\x1c.deployments.GetImageRequest\x1a\x12.deployments.Image\"\x00\x62\x06proto3')
)




_UPLOADREQUEST = _descriptor.Descriptor(
  name='UploadRequest',
  full_name='deployments.UploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageZip', full_name='deployments.UploadRequest.imageZip', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projectID', full_name='deployments.UploadRequest.projectID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jobName', full_name='deployments.UploadRequest.jobName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dockerfile', full_name='deployments.UploadRequest.dockerfile', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=123,
)


_CREATEIMAGERESPONSE = _descriptor.Descriptor(
  name='CreateImageResponse',
  full_name='deployments.CreateImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageID', full_name='deployments.CreateImageResponse.imageID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=163,
)


_GETIMAGEREQUEST = _descriptor.Descriptor(
  name='GetImageRequest',
  full_name='deployments.GetImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageTag', full_name='deployments.GetImageRequest.imageTag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projectID', full_name='deployments.GetImageRequest.projectID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=219,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='deployments.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageID', full_name='deployments.Image.imageID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projectID', full_name='deployments.Image.projectID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jobName', full_name='deployments.Image.jobName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dockerfile', full_name='deployments.Image.dockerfile', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageTag', full_name='deployments.Image.imageTag', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=319,
)

DESCRIPTOR.message_types_by_name['UploadRequest'] = _UPLOADREQUEST
DESCRIPTOR.message_types_by_name['CreateImageResponse'] = _CREATEIMAGERESPONSE
DESCRIPTOR.message_types_by_name['GetImageRequest'] = _GETIMAGEREQUEST
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadRequest = _reflection.GeneratedProtocolMessageType('UploadRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADREQUEST,
  __module__ = 'deployments_pb2'
  # @@protoc_insertion_point(class_scope:deployments.UploadRequest)
  ))
_sym_db.RegisterMessage(UploadRequest)

CreateImageResponse = _reflection.GeneratedProtocolMessageType('CreateImageResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEIMAGERESPONSE,
  __module__ = 'deployments_pb2'
  # @@protoc_insertion_point(class_scope:deployments.CreateImageResponse)
  ))
_sym_db.RegisterMessage(CreateImageResponse)

GetImageRequest = _reflection.GeneratedProtocolMessageType('GetImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETIMAGEREQUEST,
  __module__ = 'deployments_pb2'
  # @@protoc_insertion_point(class_scope:deployments.GetImageRequest)
  ))
_sym_db.RegisterMessage(GetImageRequest)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'deployments_pb2'
  # @@protoc_insertion_point(class_scope:deployments.Image)
  ))
_sym_db.RegisterMessage(Image)



_DEPLOYMENTS = _descriptor.ServiceDescriptor(
  name='Deployments',
  full_name='deployments.Deployments',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=322,
  serialized_end=473,
  methods=[
  _descriptor.MethodDescriptor(
    name='Upload',
    full_name='deployments.Deployments.Upload',
    index=0,
    containing_service=None,
    input_type=_UPLOADREQUEST,
    output_type=_CREATEIMAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetImage',
    full_name='deployments.Deployments.GetImage',
    index=1,
    containing_service=None,
    input_type=_GETIMAGEREQUEST,
    output_type=_IMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEPLOYMENTS)

DESCRIPTOR.services_by_name['Deployments'] = _DEPLOYMENTS

# @@protoc_insertion_point(module_scope)
