# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jobs.proto',
  package='jobs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\njobs.proto\x12\x04jobs\"\xe0\x01\n\x0bJobRevision\x12\x15\n\rjobRevisionID\x18\x01 \x01(\t\x12\x14\n\x0cminInstances\x18\x02 \x01(\x05\x12\x14\n\x0cmaxInstances\x18\x03 \x01(\x05\x12\r\n\x05ports\x18\x06 \x03(\x05\x12/\n\x07\x65nvVars\x18\x07 \x03(\x0b\x32\x1e.jobs.JobRevision.EnvVarsEntry\x12\x0c\n\x04name\x18\n \x01(\t\x12\x10\n\x08imageTag\x18\x0b \x01(\t\x1a.\n\x0c\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"J\n\x15\x41\x64\x64JobRevisionRequest\x12\x11\n\tprojectID\x18\x01 \x01(\t\x12\x1e\n\x03job\x18\x02 \x01(\x0b\x32\x11.jobs.JobRevision\"/\n\x16\x41\x64\x64JobRevisionResponse\x12\x15\n\rjobRevisionID\x18\x01 \x01(\t\"+\n\x16GetJobRevisionsRequest\x12\x11\n\tprojectID\x18\x01 \x01(\t\":\n\x17GetJobRevisionsResponse\x12\x1f\n\x04jobs\x18\x01 \x03(\x0b\x32\x11.jobs.JobRevision\"=\n\x19GetJobRevisionByIDRequest\x12\x11\n\tprojectID\x18\x01 \x01(\t\x12\r\n\x05jobID\x18\x02 \x01(\t\"9\n\x15RunJobRevisionRequest\x12\x11\n\tprojectID\x18\x01 \x01(\t\x12\r\n\x05jobID\x18\x02 \x01(\t2\x83\x03\n\x04Jobs\x12M\n\x0e\x41\x64\x64JobRevision\x12\x1b.jobs.AddJobRevisionRequest\x1a\x1c.jobs.AddJobRevisionResponse\"\x00\x12P\n\x0fGetJobRevisions\x12\x1c.jobs.GetJobRevisionsRequest\x1a\x1d.jobs.GetJobRevisionsResponse\"\x00\x12J\n\x12GetJobRevisionByID\x12\x1f.jobs.GetJobRevisionByIDRequest\x1a\x11.jobs.JobRevision\"\x00\x12J\n\x15GetCurrentJobRevision\x12\x1c.jobs.GetJobRevisionsRequest\x1a\x11.jobs.JobRevision\"\x00\x12\x42\n\x0eRunJobRevision\x12\x1b.jobs.RunJobRevisionRequest\x1a\x11.jobs.JobRevision\"\x00\x62\x06proto3')
)




_JOBREVISION_ENVVARSENTRY = _descriptor.Descriptor(
  name='EnvVarsEntry',
  full_name='jobs.JobRevision.EnvVarsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='jobs.JobRevision.EnvVarsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='jobs.JobRevision.EnvVarsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=245,
)

_JOBREVISION = _descriptor.Descriptor(
  name='JobRevision',
  full_name='jobs.JobRevision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobRevisionID', full_name='jobs.JobRevision.jobRevisionID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minInstances', full_name='jobs.JobRevision.minInstances', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxInstances', full_name='jobs.JobRevision.maxInstances', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ports', full_name='jobs.JobRevision.ports', index=3,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='envVars', full_name='jobs.JobRevision.envVars', index=4,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='jobs.JobRevision.name', index=5,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageTag', full_name='jobs.JobRevision.imageTag', index=6,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_JOBREVISION_ENVVARSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=245,
)


_ADDJOBREVISIONREQUEST = _descriptor.Descriptor(
  name='AddJobRevisionRequest',
  full_name='jobs.AddJobRevisionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='projectID', full_name='jobs.AddJobRevisionRequest.projectID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='job', full_name='jobs.AddJobRevisionRequest.job', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=321,
)


_ADDJOBREVISIONRESPONSE = _descriptor.Descriptor(
  name='AddJobRevisionResponse',
  full_name='jobs.AddJobRevisionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobRevisionID', full_name='jobs.AddJobRevisionResponse.jobRevisionID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=370,
)


_GETJOBREVISIONSREQUEST = _descriptor.Descriptor(
  name='GetJobRevisionsRequest',
  full_name='jobs.GetJobRevisionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='projectID', full_name='jobs.GetJobRevisionsRequest.projectID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=415,
)


_GETJOBREVISIONSRESPONSE = _descriptor.Descriptor(
  name='GetJobRevisionsResponse',
  full_name='jobs.GetJobRevisionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobs', full_name='jobs.GetJobRevisionsResponse.jobs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=475,
)


_GETJOBREVISIONBYIDREQUEST = _descriptor.Descriptor(
  name='GetJobRevisionByIDRequest',
  full_name='jobs.GetJobRevisionByIDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='projectID', full_name='jobs.GetJobRevisionByIDRequest.projectID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jobID', full_name='jobs.GetJobRevisionByIDRequest.jobID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=477,
  serialized_end=538,
)


_RUNJOBREVISIONREQUEST = _descriptor.Descriptor(
  name='RunJobRevisionRequest',
  full_name='jobs.RunJobRevisionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='projectID', full_name='jobs.RunJobRevisionRequest.projectID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jobID', full_name='jobs.RunJobRevisionRequest.jobID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=597,
)

_JOBREVISION_ENVVARSENTRY.containing_type = _JOBREVISION
_JOBREVISION.fields_by_name['envVars'].message_type = _JOBREVISION_ENVVARSENTRY
_ADDJOBREVISIONREQUEST.fields_by_name['job'].message_type = _JOBREVISION
_GETJOBREVISIONSRESPONSE.fields_by_name['jobs'].message_type = _JOBREVISION
DESCRIPTOR.message_types_by_name['JobRevision'] = _JOBREVISION
DESCRIPTOR.message_types_by_name['AddJobRevisionRequest'] = _ADDJOBREVISIONREQUEST
DESCRIPTOR.message_types_by_name['AddJobRevisionResponse'] = _ADDJOBREVISIONRESPONSE
DESCRIPTOR.message_types_by_name['GetJobRevisionsRequest'] = _GETJOBREVISIONSREQUEST
DESCRIPTOR.message_types_by_name['GetJobRevisionsResponse'] = _GETJOBREVISIONSRESPONSE
DESCRIPTOR.message_types_by_name['GetJobRevisionByIDRequest'] = _GETJOBREVISIONBYIDREQUEST
DESCRIPTOR.message_types_by_name['RunJobRevisionRequest'] = _RUNJOBREVISIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobRevision = _reflection.GeneratedProtocolMessageType('JobRevision', (_message.Message,), dict(

  EnvVarsEntry = _reflection.GeneratedProtocolMessageType('EnvVarsEntry', (_message.Message,), dict(
    DESCRIPTOR = _JOBREVISION_ENVVARSENTRY,
    __module__ = 'jobs_pb2'
    # @@protoc_insertion_point(class_scope:jobs.JobRevision.EnvVarsEntry)
    ))
  ,
  DESCRIPTOR = _JOBREVISION,
  __module__ = 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:jobs.JobRevision)
  ))
_sym_db.RegisterMessage(JobRevision)
_sym_db.RegisterMessage(JobRevision.EnvVarsEntry)

AddJobRevisionRequest = _reflection.GeneratedProtocolMessageType('AddJobRevisionRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDJOBREVISIONREQUEST,
  __module__ = 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:jobs.AddJobRevisionRequest)
  ))
_sym_db.RegisterMessage(AddJobRevisionRequest)

AddJobRevisionResponse = _reflection.GeneratedProtocolMessageType('AddJobRevisionResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDJOBREVISIONRESPONSE,
  __module__ = 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:jobs.AddJobRevisionResponse)
  ))
_sym_db.RegisterMessage(AddJobRevisionResponse)

GetJobRevisionsRequest = _reflection.GeneratedProtocolMessageType('GetJobRevisionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETJOBREVISIONSREQUEST,
  __module__ = 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:jobs.GetJobRevisionsRequest)
  ))
_sym_db.RegisterMessage(GetJobRevisionsRequest)

GetJobRevisionsResponse = _reflection.GeneratedProtocolMessageType('GetJobRevisionsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETJOBREVISIONSRESPONSE,
  __module__ = 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:jobs.GetJobRevisionsResponse)
  ))
_sym_db.RegisterMessage(GetJobRevisionsResponse)

GetJobRevisionByIDRequest = _reflection.GeneratedProtocolMessageType('GetJobRevisionByIDRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETJOBREVISIONBYIDREQUEST,
  __module__ = 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:jobs.GetJobRevisionByIDRequest)
  ))
_sym_db.RegisterMessage(GetJobRevisionByIDRequest)

RunJobRevisionRequest = _reflection.GeneratedProtocolMessageType('RunJobRevisionRequest', (_message.Message,), dict(
  DESCRIPTOR = _RUNJOBREVISIONREQUEST,
  __module__ = 'jobs_pb2'
  # @@protoc_insertion_point(class_scope:jobs.RunJobRevisionRequest)
  ))
_sym_db.RegisterMessage(RunJobRevisionRequest)


_JOBREVISION_ENVVARSENTRY._options = None

_JOBS = _descriptor.ServiceDescriptor(
  name='Jobs',
  full_name='jobs.Jobs',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=600,
  serialized_end=987,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddJobRevision',
    full_name='jobs.Jobs.AddJobRevision',
    index=0,
    containing_service=None,
    input_type=_ADDJOBREVISIONREQUEST,
    output_type=_ADDJOBREVISIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetJobRevisions',
    full_name='jobs.Jobs.GetJobRevisions',
    index=1,
    containing_service=None,
    input_type=_GETJOBREVISIONSREQUEST,
    output_type=_GETJOBREVISIONSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetJobRevisionByID',
    full_name='jobs.Jobs.GetJobRevisionByID',
    index=2,
    containing_service=None,
    input_type=_GETJOBREVISIONBYIDREQUEST,
    output_type=_JOBREVISION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCurrentJobRevision',
    full_name='jobs.Jobs.GetCurrentJobRevision',
    index=3,
    containing_service=None,
    input_type=_GETJOBREVISIONSREQUEST,
    output_type=_JOBREVISION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RunJobRevision',
    full_name='jobs.Jobs.RunJobRevision',
    index=4,
    containing_service=None,
    input_type=_RUNJOBREVISIONREQUEST,
    output_type=_JOBREVISION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JOBS)

DESCRIPTOR.services_by_name['Jobs'] = _JOBS

# @@protoc_insertion_point(module_scope)
