# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jobs_pb2 as jobs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='runner.proto',
  package='runner',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0crunner.proto\x12\x06runner\x1a\njobs.proto\"[\n\x10PushImageRequest\x12\x11\n\tprojectID\x18\x01 \x01(\t\x12\x0f\n\x07imageID\x18\x02 \x01(\t\x12\x0f\n\x07jobName\x18\x03 \x01(\t\x12\x12\n\ndockerfile\x18\x04 \x01(\t\"%\n\x11PushImageResponse\x12\x10\n\x08imageTag\x18\x01 \x01(\t\"\x13\n\x11\x44\x65ployJobResponse2\xd1\x01\n\x06Runner\x12\x42\n\tPushImage\x12\x18.runner.PushImageRequest\x1a\x19.runner.PushImageResponse\"\x00\x12?\n\rRunDeployment\x12\x11.jobs.JobRevision\x1a\x19.runner.DeployJobResponse\"\x00\x12\x42\n\x10\x44\x65leteDeployment\x12\x11.jobs.JobRevision\x1a\x19.runner.DeployJobResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[jobs__pb2.DESCRIPTOR,])




_PUSHIMAGEREQUEST = _descriptor.Descriptor(
  name='PushImageRequest',
  full_name='runner.PushImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='projectID', full_name='runner.PushImageRequest.projectID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageID', full_name='runner.PushImageRequest.imageID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jobName', full_name='runner.PushImageRequest.jobName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dockerfile', full_name='runner.PushImageRequest.dockerfile', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=127,
)


_PUSHIMAGERESPONSE = _descriptor.Descriptor(
  name='PushImageResponse',
  full_name='runner.PushImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageTag', full_name='runner.PushImageResponse.imageTag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=166,
)


_DEPLOYJOBRESPONSE = _descriptor.Descriptor(
  name='DeployJobResponse',
  full_name='runner.DeployJobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['PushImageRequest'] = _PUSHIMAGEREQUEST
DESCRIPTOR.message_types_by_name['PushImageResponse'] = _PUSHIMAGERESPONSE
DESCRIPTOR.message_types_by_name['DeployJobResponse'] = _DEPLOYJOBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PushImageRequest = _reflection.GeneratedProtocolMessageType('PushImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUSHIMAGEREQUEST,
  __module__ = 'runner_pb2'
  # @@protoc_insertion_point(class_scope:runner.PushImageRequest)
  ))
_sym_db.RegisterMessage(PushImageRequest)

PushImageResponse = _reflection.GeneratedProtocolMessageType('PushImageResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUSHIMAGERESPONSE,
  __module__ = 'runner_pb2'
  # @@protoc_insertion_point(class_scope:runner.PushImageResponse)
  ))
_sym_db.RegisterMessage(PushImageResponse)

DeployJobResponse = _reflection.GeneratedProtocolMessageType('DeployJobResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYJOBRESPONSE,
  __module__ = 'runner_pb2'
  # @@protoc_insertion_point(class_scope:runner.DeployJobResponse)
  ))
_sym_db.RegisterMessage(DeployJobResponse)



_RUNNER = _descriptor.ServiceDescriptor(
  name='Runner',
  full_name='runner.Runner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=190,
  serialized_end=399,
  methods=[
  _descriptor.MethodDescriptor(
    name='PushImage',
    full_name='runner.Runner.PushImage',
    index=0,
    containing_service=None,
    input_type=_PUSHIMAGEREQUEST,
    output_type=_PUSHIMAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RunDeployment',
    full_name='runner.Runner.RunDeployment',
    index=1,
    containing_service=None,
    input_type=jobs__pb2._JOBREVISION,
    output_type=_DEPLOYJOBRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteDeployment',
    full_name='runner.Runner.DeleteDeployment',
    index=2,
    containing_service=None,
    input_type=jobs__pb2._JOBREVISION,
    output_type=_DEPLOYJOBRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RUNNER)

DESCRIPTOR.services_by_name['Runner'] = _RUNNER

# @@protoc_insertion_point(module_scope)
