# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import jobs_pb2 as jobs__pb2
import runner_pb2 as runner__pb2


class RunnerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PushImage = channel.unary_unary(
        '/runner.Runner/PushImage',
        request_serializer=runner__pb2.PushImageRequest.SerializeToString,
        response_deserializer=runner__pb2.PushImageResponse.FromString,
        )
    self.RunDeployment = channel.unary_unary(
        '/runner.Runner/RunDeployment',
        request_serializer=jobs__pb2.JobRevision.SerializeToString,
        response_deserializer=runner__pb2.DeployJobResponse.FromString,
        )
    self.DeleteDeployment = channel.unary_unary(
        '/runner.Runner/DeleteDeployment',
        request_serializer=jobs__pb2.JobRevision.SerializeToString,
        response_deserializer=runner__pb2.DeployJobResponse.FromString,
        )


class RunnerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PushImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunDeployment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteDeployment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RunnerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PushImage': grpc.unary_unary_rpc_method_handler(
          servicer.PushImage,
          request_deserializer=runner__pb2.PushImageRequest.FromString,
          response_serializer=runner__pb2.PushImageResponse.SerializeToString,
      ),
      'RunDeployment': grpc.unary_unary_rpc_method_handler(
          servicer.RunDeployment,
          request_deserializer=jobs__pb2.JobRevision.FromString,
          response_serializer=runner__pb2.DeployJobResponse.SerializeToString,
      ),
      'DeleteDeployment': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteDeployment,
          request_deserializer=jobs__pb2.JobRevision.FromString,
          response_serializer=runner__pb2.DeployJobResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'runner.Runner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
