project: "example-project"
jobs:
  - name: "example"
    min_instances: 1
    max_instances: 1
    directory: "."
    image: "gcr.io/harambe-6/5d75c816ff556e0013de1252-example:01DNR8Q9SERPA9Z68A1AAXFXB8"
    # TODO: support language versioning
    # TODO: support language: "dockerfile"
    language: "python"
    # TODO: specify image if exists
    # TODO: specify healthcheck port
    ports:
      - 8080
    env:
      # TODO: get env from secrets
      foo: "bar"
    build:
      # TODO: CI pipeline support?
      - "pip install -r requirements.txt"
    run: "python app.py"
