deployment:
  - name: "example"
    # TODO: support language versioning
    # TODO: support language: "dockerfile"
    language: "python"
    # TODO: specify image if exists
    # TODO: specify healthcheck port
    ports:
      - 8080
    env:
      # TODO: get env from secrets
      - foo: "bar"
    build:
      # TODO: CI pipeline support?
      - "pip install -r requirements.txt"
    run: "python app.py"
